import Head from "next/head";
import { SlSocialInstagram } from "react-icons/sl";
import {
  TiSocialFacebook,
  TiSocialLinkedin,
  TiSocialPinterest,
  TiSocialSkype,
  TiSocialTwitter,
} from "react-icons/ti";

export default function Footer() {
  return (
    <>
      <Head>
        <title>Avion LTD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-between gap-x-20 p-14 bg-[#2A254B] text-white">
        {/* Footer Sections */}
        <div className="flex flex-col lg:flex-row justify-between px-10 w-full gap-y-10 lg:gap-y-0">
          {/* Menu and Categories Section */}
          <div className="flex flex-col lg:flex-row gap-10">
            {/* Menu Section */}
            <div className="flex flex-col gap-4">
              <h3 className="text-2xl font-thin">Menu</h3>
              <ul className="space-y-2">
                <li className="hover:underline font-thin">New arrivals</li>
                <li className="hover:underline font-thin">Best sellers</li>
                <li className="hover:underline font-thin">Recently viewed</li>
                <li className="hover:underline font-thin">Popular this week</li>
                <li className="hover:underline font-thin">All products</li>
              </ul>
            </div>

            {/* Categories Section */}
            <div className="flex flex-col gap-4">
              <h3 className="text-2xl font-thin">Categories</h3>
              <ul className="space-y-2">
                <li className="hover:underline font-thin">Crockery</li>
                <li className="hover:underline font-thin">Furniture</li>
                <li className="hover:underline font-thin">Homeware</li>
                <li className="hover:underline font-thin">Plant pots</li>
                <li className="hover:underline font-thin">Chairs</li>
                <li className="hover:underline font-thin">Crockery</li>
              </ul>
            </div>
          </div>

          {/* Our Company Section */}
          <div className="flex flex-col gap-4">
            <h3 className="text-2xl font-thin">Our company</h3>
            <ul className="space-y-2">
              <li className="hover:underline font-thin">About us</li>
              <li className="hover:underline font-thin">Vacancies</li>
              <li className="hover:underline font-thin">Contact us</li>
              <li className="hover:underline font-thin">Privacy</li>
              <li className="hover:underline font-thin">Returns policy</li>
            </ul>
          </div>

          {/* Join Our Mailing List Section */}
          <div className="flex flex-col gap-4 w-full lg:w-1/3">
            <h3 className="text-2xl font-thin text-white mb-4">Join our mailing list</h3>
            <div className="flex items-center ">
              {/* Email Input Field */}
              <input
                type="email"
                placeholder="your@email.com"
                className="bg-gray-100 bg-opacity-25 text-black text-center px-2 w-96 h-12 focus:outline-none"
              />
              {/* Sign Up Button */}
              <button className="bg-gray-100 text-[#2A254B] px-4 h-12 w-40 hover:bg-blue-600 focus:outline-none">
                Sign up
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Footer Bottom Section */}
      <div className="px-6 bg-[#2A254B] py-5">
        {/* Horizontal Line */}
        <hr className="border-t-1 border-[#9843b3] mb-6" />
        <div className="flex flex-col lg:flex-row justify-between items-center">
          {/* Copyright Section */}
          <div className="text-left text-white font-thin">
            <p>Copyright 2022 Avion LTD</p>
          </div>
          {/* Social Media Links */}
          <div className="flex gap-4 mt-4 lg:mt-0">
            <p className="hover:underline bg-white">
              <TiSocialLinkedin size={24} />
            </p>
            <p className="hover:underline bg-white">
              <TiSocialFacebook size={24} />
            </p>
            <p className="hover:underline text-white">
              <SlSocialInstagram size={24} />
            </p>
            <p className="hover:underline text-white">
              <TiSocialSkype size={24} />
            </p>
            <p className="hover:underline text-white">
              <TiSocialTwitter size={24} />
            </p>
            <p  className="hover:underline bg-white rounded-full">
              <TiSocialPinterest size={24} />
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
